### ISSUE TITLE
Refine anchor/rope graphic

### ISSUE THREAD

**Issue by Cloud7050** [rui-han-crh/Catfishing#31] opened 2024-04-04 18:23 UTC
Selector sphere mesh has been hidden, but there appeared to be some issues with the anchor/rope alignment and stuff as of yesterday. Can close if already fixed.

See also #15

**Comment by Cloud7050** [comment] 2024-04-04 18:27
During the alpha, the anchor had a white box that would stay on the map while the rope went up. Unsure if still relevant

**Comment by rui-han-crh** [comment] 2024-04-04 18:31
The anchor staying was intended. Oswald unties the rope around the anchor and ties it onto himself to get pulled back up

**Comment by Cloud7050** [comment] 2024-04-04 19:00
I see, if the rope already looks correct then can close ig

**Comment by rui-han-crh** [comment] 2024-04-05 20:13
Fixed via enhancement to #7

**Closed as completed by rui-han-crh** 2024-04-05 20:13 UTC
Labels: Bug
